import { describe, expect, it } from "@rstest/core";

import { pickResultSchema } from "@/core/pick/types";

import payload from "./fixtures/backend-result.json";

// Generated by customizations/pick-workbench/tests/test_frontend_contract.py from a real
// synced batch; the strict schema must accept every field the backend now sends.
describe("backend result contract", () => {
  it("parses a synced RealShort result with rank, posted records and data time", () => {
    const parsed = pickResultSchema.parse(payload);
    expect(parsed.ranking_version).toBe("signal-rank-v1");
    expect(parsed.matched_total).toBeGreaterThan(0);
    expect(parsed.data_as_of?.shared).toBe(true);
    expect(parsed.items[0]?.evidence[0]?.rank).toBe(1);
    expect(parsed.items[0]?.posted?.matched).toBe(false);
    expect(parsed.conditions.posted_account).toBe("other");
  });

  // P4-1: the fixture is written with PICK_EMIT_MIRROR_VERSION on (null: SQLite
  // never pairs a mirror); switched off, the gateway leaves the key out.
  it("parses data_as_of with the mirror_version switch on and off", () => {
    expect(payload.data_as_of).toHaveProperty("mirror_version", null);
    expect(pickResultSchema.parse(payload).data_as_of?.mirror_version).toBe(
      null,
    );
    const switchedOff = Object.fromEntries(
      Object.entries(payload.data_as_of).filter(
        ([key]) => key !== "mirror_version",
      ),
    );
    const parsed = pickResultSchema.parse({
      ...payload,
      data_as_of: switchedOff,
    });
    expect(parsed.data_as_of).not.toHaveProperty("mirror_version");
    expect(parsed.data_as_of?.shared).toBe(true);
  });
});
