import { describe, expect, it } from "@rstest/core";

import { pickResultSchema } from "@/core/pick/types";

import payload from "./fixtures/backend-result.json";

// Generated by customizations/pick-workbench/tests/test_frontend_contract.py from a real
// synced batch; the strict schema must accept every field the backend now sends.
describe("backend result contract", () => {
  it("parses a synced RealShort result with rank, posted records and data time", () => {
    const parsed = pickResultSchema.parse(payload);
    expect(parsed.ranking_version).toBe("signal-rank-v1");
    expect(parsed.matched_total).toBeGreaterThan(0);
    expect(parsed.data_as_of?.shared).toBe(true);
    expect(parsed.items[0]?.evidence[0]?.rank).toBe(1);
    expect(parsed.items[0]?.posted?.matched).toBe(false);
    expect(parsed.conditions.posted_account).toBe("other");
  });
});
