import { afterEach, expect, it, rs } from "@rstest/core";
import { cleanup, render } from "@testing-library/react";
import type { ReactNode } from "react";

import { RankFilters } from "@/components/workspace/pick-board/rank-filters";
import {
  Filters,
  Pager,
  Tabs,
  pickHref,
  rowHref,
} from "@/components/workspace/pick-board/toolbar";
import { parsePickRequest } from "@/core/pick-board/request";

import { boardRules, rankMeta, request } from "./fixtures";

rs.mock("next/link", () => ({
  default: ({
    href,
    prefetch: _prefetch,
    children,
    ...props
  }: {
    href: string;
    prefetch?: boolean;
    children: ReactNode;
  }) => (
    <a href={href} {...props}>
      {children}
    </a>
  ),
}));
afterEach(cleanup);
const rules = boardRules();
const params = (href: string) => new URLSearchParams(href.split("?")[1]);

it("all catalog pages generated by the pager remain reachable", () => {
  const req = request({ tab: "all", page: "500" });
  const { getByText } = render(
    <Pager req={req} total={73682} count={50} hasMore />,
  );
  for (const [label, page] of [
    ["1474", 1474],
    ["下一页", 501],
  ] as const) {
    const href = getByText(label).getAttribute("href")!;
    expect(parsePickRequest(params(href)).page).toBe(page);
  }
});

it("entering rankings clears a catalog search rather than hiding it", () => {
  const { getByText } = render(
    <Tabs req={request({ tab: "all", q: "Bride" })} />,
  );
  expect(params(getByText("榜单").getAttribute("href")!).has("q")).toBe(false);
});

it("a directly linked ranking search is visible and can be cleared", () => {
  const { getByText } = render(
    <RankFilters
      req={request({ tab: "rank", rk: "rs_rr", q: "Bride" })}
      meta={rankMeta()}
      rules={rules}
    />,
  );
  expect(getByText(/Bride/)).toBeTruthy();
  const cleared = params(getByText("清除搜索").getAttribute("href")!);
  expect(cleared.has("q")).toBe(false);
  expect(cleared.get("rk")).toBe("rs_rr");
});

it.each(["kd", "qc", "qr"])("%s exposes historical daily periods", (rk) => {
  const { container } = render(
    <RankFilters
      req={request({ tab: "rank", rk })}
      meta={rankMeta({ days: ["2026-09-24", "2026-09-23"], day: "2026-09-24" })}
      rules={rules}
    />,
  );
  const days = Array.from(container.querySelectorAll("a")).map((a) =>
    params(a.href).get("day"),
  );
  expect(days).toContain("2026-09-23");
});

const langs = [
  "英语",
  "西班牙语",
  "繁体中文",
  "日语",
  "印尼语",
  "泰语",
  "葡萄牙语",
  "法语",
  "韩语",
  "德语",
  "阿拉伯语",
  "意大利语",
  "土耳其语",
  "俄语",
  "越南语",
  "简体中文",
  "",
];
const facets = {
  platforms: {},
  langs: langs.map((lang) => ({ lang, n: 62 })),
  bases: {},
  posted: { no: 0, yes: 0, pool: 0 },
};

it("every language including a selected minority language remains selectable", () => {
  const { container } = render(
    <Filters
      req={request({ tab: "all", lang: "越南语" })}
      facets={facets}
      rules={rules}
    />,
  );
  const links = Array.from(container.querySelectorAll("a"));
  expect(
    links
      .find((a) => a.textContent?.startsWith("越南语"))
      ?.getAttribute("aria-current"),
  ).toBe("true");
  expect(links.some((a) => a.textContent?.startsWith("简体中文"))).toBe(true);
});

it("an unknown-language filter round trips distinctly from all languages", () => {
  const { container } = render(
    <Filters req={request({ tab: "all" })} facets={facets} rules={rules} />,
  );
  const link = Array.from(container.querySelectorAll("a")).find((a) =>
    a.textContent?.startsWith("未标语种"),
  );
  expect(link).toBeDefined();
  const selected = parsePickRequest(params(link!.href));
  expect(selected.lang).toBe("__unknown__");
  expect(link!.getAttribute("aria-current")).not.toBe("true");
});

it("a selected language remains visible when other filters leave it with no rows", () => {
  const { container } = render(
    <Filters
      req={request({ tab: "all", lang: "越南语" })}
      facets={{ ...facets, langs: [] }}
      rules={rules}
    />,
  );
  const selected = Array.from(container.querySelectorAll("a")).find((a) =>
    a.textContent?.startsWith("越南语"),
  );
  expect(selected?.getAttribute("aria-current")).toBe("true");
});

it("replay details return to the same candidate identity, version and page", () => {
  const result = "a".repeat(32);
  const original = request({ result, page: "2", v: "10" });
  const detail = parsePickRequest(params(rowHref(original, "kalos-demo-1")));
  const back = parsePickRequest(
    params(
      pickHref(detail, { tab: detail.from, rowKey: "", page: detail.page }),
    ),
  );
  expect(detail.result).toBe(result);
  expect(back).toMatchObject({ tab: "pick", result, page: 2, v: 10 });
});
