"""The replay answer the pick data board's replay tests read (P4-2, critique B22).

board_replay_cases.json holds what GET /api/pick/replay answers for a result with the agent's default conditions on
board_fixture's current version (v2): its v1 pull (gate_world's V1_CANDIDATES, worked out by hand with feed-map's
semantics, plus the two list-only candidates) parsed the way a sync imports it, in catalog_rows' identity order, and
re-run by selection.replay_view. The frontend decodes those identities in replay.integration.test.ts and compares them
with the 选剧 tab's default rows on the same board; replay.test.ts parses the same body. Nothing in the file is
written by hand: PICK_WRITE_REPLAY_CASES=1 rewrites it from the code, and otherwise it must equal what the code gives.

This is not where the guarantee comes from. That is P2's gate G8 (gates.py: a version's candidates, has_signal and no
off_on, are exactly the v1 rows of its pair, with the same signal kinds and posted records) and P4-4's check of real
cards. Here only the board's reading of one pair is shown to agree with the agent's.
"""

import json
import os
from pathlib import Path

import board_fixture as bf
import gate_world as gw

from ggwork_pick.contracts import PickConditions
from ggwork_pick.imports import parse_catalog
from ggwork_pick.mirror.gates import row_key_of
from ggwork_pick.repository import DATA_AS_OF_KEYS
from ggwork_pick.selection import RANKING_VERSION, RULE_VERSION, replay_view

CASES_FILE = Path(__file__).resolve().parents[1] / "fixtures" / "board_replay_cases.json"
WRITE_ENV = "PICK_WRITE_REPLAY_CASES"
# Stand-ins for what a real stored result carries: ids are uuid4().hex and batch ids are the repository's.
RESULT_ID = "0123456789abcdef0123456789abcdef"
CATALOG_BATCH_ID = "board-v2-catalog"
KNOWLEDGE_BATCH_ID = "board-v2-knowledge"
COMMENT = (
    "Generated by customizations/pick-workbench/tests/mirror/test_board_replay_cases.py "
    "(PICK_WRITE_REPLAY_CASES=1): GET /api/pick/replay for default conditions on board_fixture's v2 v1 pull. Synthetic."
)


def _v1_catalog_rows() -> list[dict]:
    """board_fixture's v2 pull as catalog_rows returns it: parsed like a sync (no verbatim copy), in identity order."""
    world = bf.board_world(bf.V2_TITLE, "no", bf.AS_OF["v2"])
    payload = json.dumps(list(world.v1_rows), ensure_ascii=False).encode("utf-8")
    return sorted(parse_catalog(payload, "json", keep_original=False), key=lambda row: row["identity"])


def _data_as_of() -> dict:
    """The frozen data_as_of of a result on the v2 pair, in the DATA_AS_OF_KEYS shape (freshness as the sync stores it)."""
    moment = bf.as_of_text(bf.AS_OF["v2"])
    return {"source_as_of": moment, "published_at": "2026-09-23T22:45:00.000000+00:00", "freshness": {}, "scope": "全部候选", "shared": True}


def replay_case() -> dict:
    conditions = PickConditions().model_dump()
    record = {
        "id": RESULT_ID,
        "catalog_batch_id": CATALOG_BATCH_ID,
        "knowledge_batch_id": KNOWLEDGE_BATCH_ID,
        # The fixture's version ids depend on the cluster's sequence; the view never reads this one from the file.
        "mirror_version": None,
        "conditions_json": conditions,
        "excluded_json": [],
        "rule_version": RULE_VERSION,
        "ranking_version": RANKING_VERSION,
    }
    replay = {**replay_view(record, _v1_catalog_rows()), "data_as_of": _data_as_of()}
    return {"comment": COMMENT, "replay": replay, "conditions": conditions, "row_keys": [row_key_of(json.loads(i)[1]) for i in replay["identities"]]}


def test_the_shared_replay_case_is_what_the_code_answers():
    case = replay_case()
    if os.environ.get(WRITE_ENV):
        CASES_FILE.write_text(json.dumps(case, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    assert json.loads(CASES_FILE.read_text(encoding="utf-8")) == case


def test_the_case_is_every_hand_worked_v1_candidate_of_the_board():
    case = replay_case()
    replay = case["replay"]
    # gate_world's candidates under board_fixture's book ids, and the two list-only rows board_fixture adds.
    expected = {bf._v1_key(key) for key in gw.V1_CANDIDATES} | {key for key, _ in bf.LIST_ONLY_ROWS}
    assert set(case["row_keys"]) == expected and len(case["row_keys"]) == len(expected)
    assert replay["total"] == len(replay["identities"]) == len(expected) and replay["truncated"] is False
    # The delisted c-4 and the signal-less c-3 are mirror rows the agent never sees.
    assert not {"c-3", "c-4"} & set(case["row_keys"])
    assert replay["shown"] == replay["identities"][: replay["limit"]]
    assert replay["unmappable"] == ["exclude_selected"]
    assert tuple(replay["data_as_of"]) == DATA_AS_OF_KEYS
